### PR TITLE
PR317 Cleanup

### PR DESCRIPTION
**Pull request by NetDwarf**
Remove Spellhandler.TooltipDelve(ref MiniDelveWriter)
Add .ShortDescription instead
Use SpellDelve for clients v1.110+

### CODE REVIEW

**Comment by NetDwarf** [comment]
This is to improve readability with the many magic numbers/strings that Broadsword uses and the weird MiniDelveWriter semantics in SpellHandler (maybe for the other users of MiniDelveWriter as well, but not yet). 

There were also many spells that still wouldn't display the description even though they had the special Live parameters, leaving players in the dark of what the spell does or what values they have (Damage or Value usually). This also seems subject to change every now and then by Broadsword and plain using custom descriptions seems to be more robust for now. 

I am not really sure if there are any severe downsides to using "function light" (custom description), but in my limited testing it seemed to be working fine.

**Comment by jeremv42** [comment]
I think that it's better to use the description in the Spell instead of hardcoding them if we don't use the function.

**Comment by NetDwarf** [comment]
That was the implementation in PR317 and it is missing any values of the spell (db-public). It has also the disadvantage that you have to repeat the description for every spell in DB even if it's the same SpellHandler. (if you add the values in the DB it's obviously worse)

**Comment by NetDwarf** [comment]
Just a demonstration of the problem done on 1.127 with db-public.
### PR317
1-PR317
### PR317 forcing client-side descriptions
2-PR317tuned
### This PR
3-PR317Cleanup

**Pull request closed without merging**
